version: '3.8'

services:
  api:
    build: .
    ports:
      - "5000:8080"
    depends_on:
      - mssql
    environment:
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=MyLibrary;User Id=sa;Password=Alex1980!;TrustServerCertificate=True;

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Alex1980!
    ports:
      - "1434:1434"